application: calvaryslz-lutheran
version: 1
runtime: python
api_version: 1

includes:
- auth/urls.yaml
- church/urls.yaml
- school/urls.yaml
- plugins/urls.yaml

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /resources/
  static_dir: common/resources
  #expiration: "1h"


